name: Stock Brief Generator

on:
  schedule:
     # Runs at 10:30 AM IST (5:00 AM UTC) every weekday
      - cron: '0 5 * * 1-5'
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-brief:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run stock summary script
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python src/stock_summary.py
